env: "local"
http_server:
  address: "localhost:8080"
  write_timeout: 4s
  read_timeout: 4s
  idle_timeout: 60s
postgres_db:
  host: "localhost"
  port: 5431
  user: "admin"
  password: "admin"
  db: "postgres"
auth:
  token_ttl: 24h
  signing_key: "my_secret_key"

